/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace com.coveo.blitz.thrift
{
  public enum OrderingType
  {
    ASCENDING = 1,
    DESCENDING = 2,
  }
}
