/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef awesome_CONSTANTS_H
#define awesome_CONSTANTS_H

#include "awesome_types.h"



class awesomeConstants {
 public:
  awesomeConstants();

};

extern const awesomeConstants g_awesome_constants;



#endif
