// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AwesomeService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class AwesomeServiceHandler : virtual public AwesomeServiceIf {
 public:
  AwesomeServiceHandler() {
    // Your initialization goes here
  }

  /**
   * Gets data from your service. The type and format of the requests are defined in the documentation.
   * 
   * 
   * @param request
   */
  void getData(Response& _return, const Request& request) {
    // Your implementation goes here
    printf("getData\n");
  }

  void reset() {
    // Your implementation goes here
    printf("reset\n");
  }

  bool ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void handleMapReduceResult(const std::string& name, const std::string& data) {
    // Your implementation goes here
    printf("handleMapReduceResult\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AwesomeServiceHandler> handler(new AwesomeServiceHandler());
  shared_ptr<TProcessor> processor(new AwesomeServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

