/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "awesome_constants.h"



const awesomeConstants g_awesome_constants;

awesomeConstants::awesomeConstants() {
}



