//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./awesome_types');
//HELPER FUNCTIONS AND STRUCTURES

AwesomeService_getData_args = function(args) {
  this.request = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    }
  }
};
AwesomeService_getData_args.prototype = {};
AwesomeService_getData_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.request = new ttypes.Request();
        this.request.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AwesomeService_getData_args.prototype.write = function(output) {
  output.writeStructBegin('AwesomeService_getData_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRUCT, 1);
    this.request.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AwesomeService_getData_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
AwesomeService_getData_result.prototype = {};
AwesomeService_getData_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Response();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AwesomeService_getData_result.prototype.write = function(output) {
  output.writeStructBegin('AwesomeService_getData_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AwesomeService_reset_args = function(args) {
};
AwesomeService_reset_args.prototype = {};
AwesomeService_reset_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AwesomeService_reset_args.prototype.write = function(output) {
  output.writeStructBegin('AwesomeService_reset_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AwesomeService_reset_result = function(args) {
};
AwesomeService_reset_result.prototype = {};
AwesomeService_reset_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AwesomeService_reset_result.prototype.write = function(output) {
  output.writeStructBegin('AwesomeService_reset_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AwesomeService_ping_args = function(args) {
};
AwesomeService_ping_args.prototype = {};
AwesomeService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AwesomeService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('AwesomeService_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AwesomeService_ping_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
AwesomeService_ping_result.prototype = {};
AwesomeService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AwesomeService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('AwesomeService_ping_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AwesomeService_handleMapReduceResult_args = function(args) {
  this.name = null;
  this.data = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.data !== undefined) {
      this.data = args.data;
    }
  }
};
AwesomeService_handleMapReduceResult_args.prototype = {};
AwesomeService_handleMapReduceResult_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.data = input.readBinary();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AwesomeService_handleMapReduceResult_args.prototype.write = function(output) {
  output.writeStructBegin('AwesomeService_handleMapReduceResult_args');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.data !== null && this.data !== undefined) {
    output.writeFieldBegin('data', Thrift.Type.STRING, 2);
    output.writeBinary(this.data);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AwesomeService_handleMapReduceResult_result = function(args) {
};
AwesomeService_handleMapReduceResult_result.prototype = {};
AwesomeService_handleMapReduceResult_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AwesomeService_handleMapReduceResult_result.prototype.write = function(output) {
  output.writeStructBegin('AwesomeService_handleMapReduceResult_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AwesomeServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
AwesomeServiceClient.prototype = {};
AwesomeServiceClient.prototype.seqid = function() { return this._seqid; }
AwesomeServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
AwesomeServiceClient.prototype.getData = function(request, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getData(request);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getData(request);
  }
};

AwesomeServiceClient.prototype.send_getData = function(request) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getData', Thrift.MessageType.CALL, this.seqid());
  var args = new AwesomeService_getData_args();
  args.request = request;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AwesomeServiceClient.prototype.recv_getData = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AwesomeService_getData_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getData failed: unknown result');
};
AwesomeServiceClient.prototype.reset = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_reset();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_reset();
  }
};

AwesomeServiceClient.prototype.send_reset = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('reset', Thrift.MessageType.CALL, this.seqid());
  var args = new AwesomeService_reset_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AwesomeServiceClient.prototype.recv_reset = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AwesomeService_reset_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
AwesomeServiceClient.prototype.ping = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_ping();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_ping();
  }
};

AwesomeServiceClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid());
  var args = new AwesomeService_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AwesomeServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AwesomeService_ping_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ping failed: unknown result');
};
AwesomeServiceClient.prototype.handleMapReduceResult = function(name, data, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_handleMapReduceResult(name, data);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_handleMapReduceResult(name, data);
  }
};

AwesomeServiceClient.prototype.send_handleMapReduceResult = function(name, data) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('handleMapReduceResult', Thrift.MessageType.CALL, this.seqid());
  var args = new AwesomeService_handleMapReduceResult_args();
  args.name = name;
  args.data = data;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AwesomeServiceClient.prototype.recv_handleMapReduceResult = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AwesomeService_handleMapReduceResult_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
AwesomeServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
AwesomeServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

AwesomeServiceProcessor.prototype.process_getData = function(seqid, input, output) {
  var args = new AwesomeService_getData_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getData.length === 1) {
    Q.fcall(this._handler.getData, args.request)
      .then(function(result) {
        var result = new AwesomeService_getData_result({success: result});
        output.writeMessageBegin("getData", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new AwesomeService_getData_result(err);
        output.writeMessageBegin("getData", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getData(args.request,  function (err, result) {
      var result = new AwesomeService_getData_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getData", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AwesomeServiceProcessor.prototype.process_reset = function(seqid, input, output) {
  var args = new AwesomeService_reset_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.reset.length === 0) {
    Q.fcall(this._handler.reset)
      .then(function(result) {
        var result = new AwesomeService_reset_result({success: result});
        output.writeMessageBegin("reset", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new AwesomeService_reset_result(err);
        output.writeMessageBegin("reset", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.reset( function (err, result) {
      var result = new AwesomeService_reset_result((err != null ? err : {success: result}));
      output.writeMessageBegin("reset", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AwesomeServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new AwesomeService_ping_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.ping.length === 0) {
    Q.fcall(this._handler.ping)
      .then(function(result) {
        var result = new AwesomeService_ping_result({success: result});
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new AwesomeService_ping_result(err);
        output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.ping( function (err, result) {
      var result = new AwesomeService_ping_result((err != null ? err : {success: result}));
      output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

AwesomeServiceProcessor.prototype.process_handleMapReduceResult = function(seqid, input, output) {
  var args = new AwesomeService_handleMapReduceResult_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.handleMapReduceResult.length === 2) {
    Q.fcall(this._handler.handleMapReduceResult, args.name, args.data)
      .then(function(result) {
        var result = new AwesomeService_handleMapReduceResult_result({success: result});
        output.writeMessageBegin("handleMapReduceResult", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new AwesomeService_handleMapReduceResult_result(err);
        output.writeMessageBegin("handleMapReduceResult", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.handleMapReduceResult(args.name, args.data,  function (err, result) {
      var result = new AwesomeService_handleMapReduceResult_result((err != null ? err : {success: result}));
      output.writeMessageBegin("handleMapReduceResult", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

